name: "stress"

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    paths-ignore:
      - 'browser_patches/**'
      - 'docs/**'
    types: [ labeled ]
    branches:
      - main
      - release-*

env:
  FORCE_COLOR: 1
  ELECTRON_SKIP_BINARY_DOWNLOAD: 1

jobs:
  test_components:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
    - run: npx playwright install --with-deps
    - run: npx playwright install firefox-asan
      if: matrix.os != 'windows-latest'
    - run: npm run stest contexts -- --project=chromium
      if: always()
    - run: npm run stest browsers -- --project=chromium
      if: always()
    - run: npm run stest frames -- --project=chromium
      if: always()
    - run: npm run stest contexts -- --project=webkit
      if: always()
    - run: npm run stest browsers -- --project=webkit
      if: always()
    - run: npm run stest frames -- --project=webkit
      if: always()
    - run: npm run stest contexts -- --project=firefox
      if: always()
    - run: npm run stest browsers -- --project=firefox
      if: always()
    - run: npm run stest frames -- --project=firefox
      if: always()
    - run: npm run stest heap -- --project=chromium
      if: always()
