name: "Trigger: Chromium with Symbols Builds"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  trigger:
    name: "trigger"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Get Chromium revision
      id: chromium-version
      run: |
        REVISION=$(node -e "console.log(require('./packages/playwright-core/browsers.json').browsers.find(b => b.name === 'chromium-with-symbols').revision)")
        echo "REVISION=$REVISION" >> $GITHUB_OUTPUT
    - run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${GH_TOKEN}" \
          --data "{\"event_type\": \"build_chromium_with_symbols\", \"client_payload\": {\"revision\": \"${CHROMIUM_REVISION}\"}}" \
          https://api.github.com/repos/microsoft/playwright-browsers/dispatches
      env:
        GH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_PERSONAL_ACCESS_TOKEN }}
        CHROMIUM_REVISION: ${{ steps.chromium-version.outputs.REVISION }}
